### ISSUE TITLE
Add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [JacobSeedorff21/fastbackward#1]
I suggest adding the topics `statistics`, `r-package`, `regression`, `subset-selection` in the About section, as explained at https://docs.github.com/en/enterprise-cloud@latest/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by JacobSeedorff21** [comment]
Done, thank you for the suggestion!
