### ISSUE TITLE
Tests fail on R version < 4.4.0

### ISSUE THREAD

**Issue by slager** [JacobSeedorff21/fastbackward#2]
The `%||%` operator was not added to R until R v4.4.0 so this package requires a very new version of R to work properly.

See:

https://cran.r-project.org/web/checks/check_results_fastbackward.html
https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.html

**Comment by JacobSeedorff21** [comment]
Thank you for bringing this issue to my attention. I have fixed the issue by replacing %||% with the older synax.
